# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set Python to run in unbuffered mode
ENV PYTHONUNBUFFERED 1

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir psycopg2-binary




